volumes:
  postgres_data:
  caddy_data:
  caddy_config:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evolve_backend
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: evolve_db
    env_file: .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    restart: unless-stopped
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped