volumes:
  local_postgres_data: {}
  redis_data: {}

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: evolve_backend
    volumes:
      - .:/code
    env_file: .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "8080:8000"
    depends_on:
      - db
      # - redis_service
    stdin_open: true
    tty: true
    restart: on-failure

  db:
    image: postgres:15
    container_name: evolve_db
    ports:
      - "5433:5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    restart: on-failure

  # redis_service:
  #   image: "redis:alpine"
  #   container_name: evolve_redis
  #   volumes:
  #     - redis_data:/data
  #   restart: on-failure
  #   env_file: .env

  # tests:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: evolve_tests
  #   volumes:
  #     - .:/code
  #   env_file: .env
  #   environment:
  #     - ENVIRONMENT=local
  #     - RUN_TESTS=true  # 👈 Esta variable evita que se ejecute runserver
  #     - DJANGO_SETTINGS_MODULE=config.settings.local
  #   depends_on:
  #     - db
  #   command: >
  #     sh -c "pytest --maxfail=1 --disable-warnings -v"