version: "3.9"

volumes:
  postgres_data: {}
  redis_data: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evolve_backend
    volumes:
      - .:/code
    env_file: .env.${ENVIRONMENT}
    ports:
      - "8080:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: evolve_db
    ports:
      - "5433:5432"
    env_file: .env.${ENVIRONMENT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    restart: unless-stopped
