# Generated by Django 5.2 on 2025-07-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransaccionConekta',
        ),
    ]
