# Generated by Django 5.2 on 2025-07-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_delete_transaccionconekta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del país o nacionalidad', max_length=100, unique=True)),
                ('codigo_iso', models.CharField(help_text='Código ISO alfa-2 (ej. mx, us)', max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'eventos_nacionalidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='peleador',
            name='trayectoria',
            field=models.TextField(blank=True, help_text='Texto libre donde el peleador puede describir su trayectoria deportiva', null=True),
        ),
        migrations.AlterField(
            model_name='peleador',
            name='cinta',
            field=models.CharField(choices=[('adulto_blanca', 'Blanca'), ('adulto_azul', 'Azul'), ('adulto_morada', 'Morada'), ('adulto_cafe', 'Café'), ('adulto_negra', 'Negra'), ('nino_blanca', 'Blanca (Niño)'), ('nino_blanca_amarilla', 'Blanca-Amarilla'), ('nino_amarilla', 'Amarilla'), ('nino_amarilla_naranja', 'Amarilla-Naranja'), ('nino_naranja', 'Naranja'), ('nino_naranja_verde', 'Naranja-Verde'), ('nino_verde', 'Verde')], help_text='Grado de cinta actual', max_length=50),
        ),
        migrations.AlterField(
            model_name='peleador',
            name='nacionalidad',
            field=models.ForeignKey(help_text='País de nacionalidad', on_delete=django.db.models.deletion.PROTECT, related_name='peleadores', to='eventos.nacionalidad'),
        ),
    ]
