# Generated by Django 5.2 on 2025-07-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_nacionalidad_peleador_trayectoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peleador',
            name='direccion',
            field=models.ForeignKey(help_text='Dirección actual del peleador', on_delete=django.db.models.deletion.CASCADE, related_name='peleadores', to='eventos.direccion'),
        ),
        migrations.AlterField(
            model_name='peleador',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], help_text='Género del peleador', max_length=1),
        ),
    ]
