# Generated by Django 5.2 on 2025-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_peleador_direccion_alter_peleador_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPatrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de patrocinio',
                'verbose_name_plural': 'Tipos de patrocinio',
                'db_table': 'eventos_tipo_patrocinio',
            },
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='tipo_patrocinio',
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='tipos_patrocinio',
            field=models.ManyToManyField(related_name='patrocinadores', to='eventos.tipopatrocinio'),
        ),
    ]
