# Generated by Django 5.2 on 2025-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_tipopatrocinio_remove_patrocinador_tipo_patrocinio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopatrocinio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si el tipo de patrocinio está activo'),
        ),
    ]
