# Generated by Django 5.2 on 2025-07-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_tipopatrocinio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si el patrocinador está activo en la organización'),
        ),
        migrations.AddField(
            model_name='peleador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si el peleador está activo en la organización'),
        ),
    ]
