# Generated by Django 5.2 on 2025-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_patrocinador_activo_peleador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoboleto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si el tipo de boleto está activo'),
        ),
    ]
