# Generated by Django 5.2 on 2025-07-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_tipoboleto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción del beneficio', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'db_table': 'eventos_beneficio',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tipoboleto',
            name='incluye',
        ),
        migrations.CreateModel(
            name='TipoBoletoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='¿Este beneficio está incluido en el boleto?')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_boleto', to='eventos.beneficio')),
                ('tipo_boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_beneficio', to='eventos.tipoboleto')),
            ],
            options={
                'verbose_name': 'Beneficio por tipo de boleto',
                'verbose_name_plural': 'Beneficios por tipo de boleto',
                'db_table': 'eventos_tipo_boleto_beneficio',
                'unique_together': {('tipo_boleto', 'beneficio')},
            },
        ),
    ]
