# Generated by Django 5.2 on 2025-07-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_beneficio_remove_tipoboleto_incluye_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraboleto',
            name='referencia_pago',
        ),
        migrations.CreateModel(
            name='TransaccionStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(help_text='ID de PaymentIntent en Stripe', max_length=100, unique=True)),
                ('client_secret', models.CharField(blank=True, help_text='Client secret del PaymentIntent (solo si se requiere en frontend)', max_length=255, null=True)),
                ('estatus', models.CharField(help_text='Estado de la transacción (ej. succeeded, processing, canceled)', max_length=50)),
                ('metodo_pago', models.CharField(help_text='Método de pago usado (ej. card, oxxo, spei, etc.)', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto procesado en la transacción', max_digits=10)),
                ('moneda', models.CharField(default='MXN', help_text='Moneda utilizada (ej. MXN)', max_length=10)),
                ('pagado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que se confirmó el pago', null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, help_text='Fecha de cancelación si aplica', null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error devuelto por Stripe si aplica', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Payload completo recibido de Stripe', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(help_text='Compra asociada a esta transacción', on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_stripe', to='eventos.compraboleto')),
            ],
            options={
                'verbose_name': 'Transacción con Stripe',
                'verbose_name_plural': 'Transacciones con Stripe',
                'db_table': 'pagos_transacciones_stripe',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
