# Generated by Django 5.2 on 2025-07-11 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_remove_compraboleto_referencia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la dirección'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de creación de la dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si la nacionalidad está activa'),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
