# Generated by Django 5.2 on 2025-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_direccion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peleador',
            name='apodo',
            field=models.CharField(blank=True, help_text='Sobre nombre del peleador', max_length=50, null=True),
        ),
    ]
