# Generated by Django 5.2 on 2025-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_peleador_apodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peleador',
            name='cinta',
            field=models.CharField(choices=[('blanca', 'Blanca'), ('azul', 'Azul'), ('morada', 'Morada'), ('cafe', 'Café'), ('negra', 'Negra'), ('blanca_amarilla', 'Blanca-Amarilla'), ('amarilla', 'Amarilla'), ('amarilla_naranja', 'Amarilla-Naranja'), ('naranja', 'Naranja'), ('naranja_verde', 'Naranja-Verde'), ('verde', 'Verde')], help_text='Grado de cinta actual', max_length=50),
        ),
    ]
