# Generated by Django 5.2 on 2025-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_peleador_cinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoboleto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Define si el boleto estara marcado como destacado de entre el resto'),
        ),
        migrations.AddField(
            model_name='tipoboleto',
            name='mensaje_promocional',
            field=models.CharField(default='', help_text='Define alguna promocion o ventaja añadida al boleto', max_length=50),
            preserve_default=False,
        ),
    ]
