# Generated by Django 5.2 on 2025-07-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_tipoboleto_destacado_tipoboleto_mensaje_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='logo',
            field=models.URLField(blank=True, help_text='URL del logo alojado en S3', null=True),
        ),
    ]
