# Generated by Django 5.2 on 2025-07-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_patrocinador_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peleador',
            name='foto',
            field=models.URLField(blank=True, help_text='URL de imagen de perfil alojado en S3', null=True),
        ),
    ]
