# Generated by Django 5.2 on 2025-07-29 18:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_alter_peleador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1990, 1, 1), help_text='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoletoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asistente', models.CharField(max_length=100)),
                ('fecha_nacimiento_asistente', models.DateField(help_text='Fecha de nacimiento del asistente')),
                ('email_asistente', models.EmailField(max_length=254)),
                ('foto_asistente', models.URLField(blank=True, help_text='URL de la foto del asistente alojada en S3', null=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('token_formulario', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_asignados', to='eventos.compraboleto')),
            ],
            options={
                'db_table': 'eventos_boleto_asignado',
            },
        ),
    ]
