# Generated by Django 5.2 on 2025-07-30 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_comprador_fecha_nacimiento_boletoasignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.compraboleto')),
            ],
        ),
    ]
