# Generated by Django 5.2 on 2025-07-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_tokenasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='email_asistente',
            field=models.EmailField(help_text='Correo electrónico del asistente', max_length=254, unique=True),
        ),
    ]
