# Generated by Django 5.2 on 2025-07-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_alter_boletoasignado_email_asistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='email_asistente',
            field=models.EmailField(help_text='Correo electrónico del asistente', max_length=254),
        ),
    ]
