# Generated by Django 5.2 on 2025-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_alter_boletoasignado_email_asistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='foto_asistente',
            field=models.ImageField(blank=True, help_text='Foto del asistente', null=True, upload_to='boletos/asistentes/'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa o marca', null=True, upload_to='patrocinadores/logos/'),
        ),
        migrations.AlterField(
            model_name='peleador',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del peleador', null=True, upload_to='peleadores/foto-perfil/'),
        ),
    ]
