# Generated by Django 5.2 on 2025-08-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_alter_boletoasignado_foto_asistente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenasignacion',
            options={'verbose_name': 'Token de asignación', 'verbose_name_plural': 'Tokens de asignación'},
        ),
        migrations.AlterModelTable(
            name='tokenasignacion',
            table='eventos_token_asignacion',
        ),
    ]
