# Generated by Django 5.2 on 2025-08-06 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_alter_tokenasignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenasignacion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
