# Generated by Django 5.2 on 2025-08-06 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_alter_tokenasignacion_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='token_formulario',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tokenasignacion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
