# Generated by Django 5.2 on 2025-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_alter_boletoasignado_token_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='token_formulario',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
