# Generated by Django 5.2 on 2025-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_boletoasignado_token_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletoasignado',
            name='token_formulario',
            field=models.CharField(default='token', max_length=64),
            preserve_default=False,
        ),
    ]
