# Generated by Django 5.2 on 2025-08-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_alter_boletoasignado_token_formulario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoletoAsignado',
            new_name='AsignacionBoletos',
        ),
        migrations.RenameModel(
            old_name='TokenAsignacion',
            new_name='AsignacionToken',
        ),
        migrations.AlterModelOptions(
            name='asignacionboletos',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Asignación de boleto', 'verbose_name_plural': 'Asignacion de boletos'},
        ),
        migrations.AlterModelOptions(
            name='asignaciontoken',
            options={'verbose_name': 'Asignación de token', 'verbose_name_plural': 'Asignacion de tokens'},
        ),
        migrations.AlterModelTable(
            name='asignacionboletos',
            table='eventos_asignacion_boletos',
        ),
        migrations.AlterModelTable(
            name='asignaciontoken',
            table='eventos_asignacion_token',
        ),
    ]
