# Generated by Django 5.2 on 2025-08-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_rename_boletoasignado_asignacionboletos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraboleto',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra de boleto', 'verbose_name_plural': 'Compra de boletos'},
        ),
    ]
