# Generated by Django 5.2 on 2025-05-15 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo electrónico del invitado', max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha límite para que la persona complete el registro')),
                ('fue_usado', models.BooleanField(default=False)),
                ('medio_envio', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Ambos')], default='email', help_text='Medio por el cual se envió la invitación', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono si se envió vía WhatsApp', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(blank=True, help_text='Admin o coach que envió la invitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación de usuario',
                'verbose_name_plural': 'Invitaciones de usuarios',
                'db_table': 'users_invitaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
