# Generated by Django 5.2 on 2025-07-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0001_initial'),
        ('users', '0002_remove_empleado_activo_cliente_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiales.filial'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('business_owner', 'Business Owner'), ('admin', 'Admin'), ('coach', 'Coach'), ('athlete', 'Athlete')], default='athlete', max_length=20),
        ),
    ]
