# Generated by Django 5.2 on 2025-07-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinvitation_filial_userinvitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('business_owner', 'Business Owner'), ('admin', 'Admin'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('egpro', 'EgPro')], default='athlete', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('business_owner', 'Business Owner'), ('admin', 'Admin'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('egpro', 'EgPro')], default='athlete', max_length=20),
        ),
    ]
