# Generated by Django 5.2 on 2025-07-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inicia formalmente la membresía')),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo total acordado para esta membresía', max_digits=8)),
                ('esta_activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios o notas sobre este pago, si aplica', null=True)),
                ('duracion_meses', models.PositiveSmallIntegerField(blank=True, help_text='Duración planeada en meses (usado como referencia para cálculos)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'db_table': 'inscripciones_membresias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('codigo_integracion', models.CharField(blank=True, help_text="Código para integración con servicios de pago (ej. 'stripe', 'paypal')", max_length=50, null=True)),
                ('requiere_confirmacion_manual', models.BooleanField(default=False, help_text='Indica si este método de pago requiere confirmación manual por parte del staff')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'inscripciones_metodo_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', help_text='Frecuencia con la que se realiza este pago', max_length=20)),
                ('periodo_inicio', models.DateField(help_text='Fecha de inicio del periodo que cubre este pago (ej. 2025-05-01)')),
                ('monto_recurrente', models.DecimalField(decimal_places=2, help_text='Monto total pagado en ese periodo', max_digits=8)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha real en que se realizó el pago', null=True)),
                ('dia_limite_pago', models.PositiveSmallIntegerField(default=5, help_text='Día del mes en que vence el pago (ej: día 5)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='confirmado', help_text='Estado actual del pago', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios o notas como promociones, retrasos, acuerdos especiales, etc.', null=True)),
            ],
            options={
                'verbose_name': 'Pago recurrente',
                'verbose_name_plural': 'Pagos recurrentes',
                'db_table': 'inscripciones_pago_recurrente',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Inscripción',
                'verbose_name_plural': 'Tipos de Inscripción',
                'db_table': 'inscripciones_tipo',
                'ordering': ['id'],
            },
        ),
    ]
