# Generated by Django 5.2 on 2025-05-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membresia',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscriptions.metodopago'),
        ),
        migrations.AddField(
            model_name='pagorecurrente',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inscriptions.membresia'),
        ),
        migrations.AddField(
            model_name='pagorecurrente',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membresia',
            name='tipo_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscriptions.tipoinscripcion'),
        ),
        migrations.AddConstraint(
            model_name='pagorecurrente',
            constraint=models.UniqueConstraint(fields=('membresia', 'periodo_inicio'), name='unique_pago_por_periodo'),
        ),
    ]
